package: analytics
version: '1.2.2'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/analytics

page:
    title: 'translate:title'
    perm: analytics[]
    pjax: true
    icon: rex-icon fa-bar-chart
    subpages:
        config: { title: 'translate:config', perm: analytics[config] }